"""Durable static nine-Step W4 bounded paper strategy."""

from __future__ import annotations

from dataclasses import asdict

from conflux_weave.core import (
    BudgetLedger,
    RunRecord,
    RunStatus,
    StepRecord,
    StepStatus,
    TaskSpec,
)
from conflux_weave.paper_discovery import (
    MAX_SELECTED,
    PROMPT_VERSION,
    SCHEMA_VERSION,
    WORKFLOW_VERSION,
)
from conflux_weave.planning import BOUNDED_STRATEGY_ID
from conflux_weave.runtime.bounded_paper_steps import (
    BoundedPaperStepMixin,
    PLANNER_PROMPT_VERSION,
)
from conflux_weave.runtime.durable_paper_runtime import DurablePaperDiscoveryRuntime
from conflux_weave.runtime.durable_paper_shared import _idempotency_key
from conflux_weave.runtime.sqlite import SideEffectClass, StepPolicy, SubmissionResult
from conflux_weave.runtime.worker import SQLiteStepWorker


BOUNDED_WORKFLOW_VERSION = "bounded-arxiv-paper-discovery-durable-v1"
BOUNDED_STEP_KINDS = (
    "build_context",
    "propose_plan",
    "validate_plan",
    "search_slot_1",
    "search_slot_2_or_skip",
    "merge_and_rank",
    "synthesize_claims",
    "validate_delivery",
    "publish_delivery",
)


class BoundedPaperStrategyRuntime(BoundedPaperStepMixin, DurablePaperDiscoveryRuntime):
    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.worker = SQLiteStepWorker(
            self.repository,
            self.worker.worker_id,
            self.worker.lease_seconds,
            BOUNDED_WORKFLOW_VERSION,
        )

    def submit(
        self,
        query: str,
        *,
        task_summary: str | None = None,
        inclusion_constraints: tuple[str, ...] = (),
        exclusion_constraints: tuple[str, ...] = (),
        hard_constraints: tuple[str, ...] = (),
        budget: BudgetLedger | None = None,
    ) -> SubmissionResult:
        normalized_query = query.strip()
        if not normalized_query:
            raise ValueError("query must not be empty")
        summary = (task_summary or normalized_query).strip()
        if not summary:
            raise ValueError("task_summary must not be empty")
        constraints = {
            "inclusion_constraints": self._normalize_constraints(
                inclusion_constraints, "inclusion_constraints"
            ),
            "exclusion_constraints": self._normalize_constraints(
                exclusion_constraints, "exclusion_constraints"
            ),
            "hard_constraints": self._normalize_constraints(
                hard_constraints, "hard_constraints"
            ),
        }
        task_id = self.id_factory("task")
        run_id = self.id_factory("run")
        step_ids = {kind: f"{run_id}:{kind}" for kind in BOUNDED_STEP_KINDS}
        created_at = self.clock()
        frozen_budget = budget or BudgetLedger(
            300, 40_000, 3_072, "provider-price-not-frozen", 4, 2, 1
        )
        frozen_input = {
            "query": normalized_query,
            "search_query": "generated by bounded Planner",
            "task_summary": summary,
            **{name: list(values) for name, values in constraints.items()},
            "workflow_version": BOUNDED_WORKFLOW_VERSION,
            "source_workflow_version": WORKFLOW_VERSION,
            "strategy_id": BOUNDED_STRATEGY_ID,
            "planner_prompt_version": PLANNER_PROMPT_VERSION,
            "synthesis_prompt_version": PROMPT_VERSION,
            "code_revision": self.code_revision,
            "provider": self.chat_adapter.config.provider_name,
            "model": self.chat_adapter.config.model,
            "selected_limit": MAX_SELECTED,
            "budget": asdict(frozen_budget),
        }
        config = self.artifact_store.put_json(
            {
                "schema_version": SCHEMA_VERSION,
                **frozen_input,
                "automatic_retry": False,
                "fallback": False,
                "secret_recorded": False,
                "cost_enforcement": "unavailable",
            },
            producer_step_id=step_ids["build_context"],
            schema_version=SCHEMA_VERSION,
        )
        task = TaskSpec(
            task_id=task_id,
            kind="bounded_paper_discovery",
            input=frozen_input,
            requested_policy=BOUNDED_WORKFLOW_VERSION,
            idempotency_key=_idempotency_key(frozen_input),
        )
        run = RunRecord(
            run_id=run_id,
            task_id=task_id,
            status=RunStatus.ACCEPTED,
            workflow_version=BOUNDED_WORKFLOW_VERSION,
            config_snapshot_ref=config.artifact_id,
            budget=frozen_budget,
            created_at=created_at,
            updated_at=created_at,
        )
        steps = tuple(
            StepRecord(
                step_id=step_ids[kind],
                run_id=run_id,
                kind=kind,
                attempt=1,
                status=StepStatus.PENDING,
                input_refs=(config.artifact_id,) if kind == "build_context" else (),
            )
            for kind in BOUNDED_STEP_KINDS
        )
        policies = {
            step_ids["build_context"]: StepPolicy(
                SideEffectClass.NONE, "deterministic replay"
            ),
            step_ids["propose_plan"]: StepPolicy(
                SideEffectClass.PAID_EXTERNAL_UNKNOWN,
                "never automatically replay an unknown Planner request",
            ),
            step_ids["validate_plan"]: StepPolicy(
                SideEffectClass.NONE, "deterministic fail-closed validation"
            ),
            step_ids["search_slot_1"]: StepPolicy(
                SideEffectClass.REPLAYABLE_EXTERNAL_READ,
                "reuse committed response before replay",
            ),
            step_ids["search_slot_2_or_skip"]: StepPolicy(
                SideEffectClass.REPLAYABLE_EXTERNAL_READ,
                "execute one validated search or persist skipped",
            ),
            step_ids["merge_and_rank"]: StepPolicy(
                SideEffectClass.NONE, "deterministic merge, deduplication and rank"
            ),
            step_ids["synthesize_claims"]: StepPolicy(
                SideEffectClass.PAID_EXTERNAL_UNKNOWN,
                "never automatically replay an unknown synthesis request",
            ),
            step_ids["validate_delivery"]: StepPolicy(
                SideEffectClass.NONE, "deterministic replay"
            ),
            step_ids["publish_delivery"]: StepPolicy(
                SideEffectClass.IDEMPOTENT_LOCAL_WRITE, "atomic local publication"
            ),
        }
        result = self.repository.submit_task(
            task, run, steps, step_policies=policies, submission_artifacts=(config,)
        )
        if result.created:
            self.repository.transition_run(
                result.run_id, RunStatus.QUEUED, updated_at=created_at
            )
        return result

    @staticmethod
    def _normalize_constraints(values: tuple[str, ...], field: str) -> tuple[str, ...]:
        normalized = tuple(value.strip() for value in values)
        if any(not value for value in normalized):
            raise ValueError(f"{field} must contain only non-empty strings")
        return normalized

    def _checkpoint(self, run_id: str, step_kind: str, schema: str) -> dict:
        aliases = {
            "rank_candidates": "merge_and_rank",
            "search_arxiv": "search_slot_1",
        }
        return super()._checkpoint(run_id, aliases.get(step_kind, step_kind), schema)
